name: Check Build & Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        outbox: [outbox-user, outbox-social, outbox-post, outbox-event]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./ci-tools/.github/actions/setup-node-yarn
        with:
          node-version: '24'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - name: Install dependencies
        working-directory: ${{ matrix.outbox }}
        run: yarn install

      - name: Lint
        working-directory: ${{ matrix.outbox }}
        run: yarn lint

      - name: Build
        working-directory: ${{ matrix.outbox }}
        run: yarn build
